# Generated by Django 3.2 on 2021-05-04 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding', models.CharField(max_length=120, verbose_name='boarding location')),
                ('destination', models.CharField(max_length=120, verbose_name='destination location')),
                ('flight_datetime', models.DateTimeField(verbose_name='flight date-time')),
                ('status', models.CharField(choices=[('booked', 'booked'), ('available', 'available'), ('cancelled', 'cancelled')], max_length=50, verbose_name='status')),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='flight booked by')),
            ],
        ),
    ]
