# Generated by Django 3.2 on 2021-05-04 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_datetime',
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='flight date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='flight time'),
            preserve_default=False,
        ),
    ]
